format_version: '3'
pipelines:
  deploy_ec2_pipeline:
    group: infra
    label_template: '${COUNT}'
    lock_behavior: none
    materials:
      git-repo:
        git: https://github.com/theArcianCoder/cfn-log-test.git 
        branch: main
    stages:
      - deploy:
          jobs:
            - deploy_ec2:
                tasks:
                  - exec:
                      command: ruby gocd/deploy_pipeline.rb
