Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-080e1f13689e07408  # Replace this with the desired AMI ID
      KeyName: test.pem    # Replace this with your SSH key pair

