format_version: '3'
pipelines:
  deploy_ec2_pipeline:
    group: infra
    label_template: '${COUNT}'
    lock_behavior: none
    materials:
      git-repo: 
        url: https://github.com/theArcianCoder/cfn-log-test.git 
        branch: main
    stages:
      - deploy:
          jobs:
            - deploy_ec2:
                tasks:
                  - exec:
                      command: aws cloudformation deploy --template-file cloudformation/ec2-instance.yaml --stack-name my-ec2-stack --parameter-overrides $(cat cloudformation/parameters.json | jq -r to_entries[] | map("\(.key)=\(.value|tostring)") | join(" ")) --region us-east-1
                  - exec:
                      command: aws cloudformation describe-stack-events --stack-name my-ec2-stack --region us-east-1
