format_version: '3'
pipelines:
  deploy_cfn_pipeline:
    group: infra
    label_template: '${COUNT}'
    lock_behavior: none
    materials:
      git-repo:
        git: https://github.com/yourusername/my-repo.git
        branch: master
    stages:
      - generate_template:
          jobs:
            - generate_template:
                tasks:
                  - exec:
                      command: ruby generate_template.rb
      - deploy_stack:
          jobs:
            - deploy_stack:
                tasks:
                  - exec:
                      command: ruby deploy_stack.rb
